# Generated by Django 3.2.3 on 2022-12-23 22:00

from django.db import migrations
import store.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='/Users/elias/thrift-ops/media/images/default_placeholder.png', help_text='Upload a product image', upload_to=store.models.upload_path, verbose_name='Image'),
        ),
    ]
